### ISSUE TITLE
Vessel placement mode

### ISSUE THREAD

**Issue by repwolfe** [repwolfe/ProjectMishkan#15]
When a vessel is selected to place in the Mishkan, the game should behave as follows
- The vessel should be visible in the middle of the screen, acting as a cursor
- The vessel should appear semi transparent in this mode
- Buttons to rotate the vessel should be visible
- The screen can be moved by dragging it either up/down or left/right
- There should be a button to place the vessel where it is currently hovering
- Some indicators should display if this is the wrong placement
- Some ability to cancel out of this mode

**Comment by repwolfe** [comment]
Completed in e620d61

**Comment by dovcohen** [comment]
Seriously!?

**Comment by repwolfe** [comment]
In a very basic form. Related features to improve it's functionality are still in progress.
